### ISSUE TITLE
TANGO 会开源吗？

### ISSUE THREAD

**Issue by tiptinker** [PantoMatrix/TANGO#1]
非常期待。
不知效果能不能达到国内电商直播数字人的水平 
![image](https://github.com/user-attachments/assets/5fe9478d-796a-4320-8908-4bbaa266631a)

**Comment by H-Liu1997** [comment]
hi，tango已经开源了，可以 git clone https://huggingface.co/spaces/H-Liu1997/TANGO

**Comment by tiptinker** [comment]
谢谢
